EXT_AUDIO = ['.wav', '.mp3', '.raw', '.aac', '.wav', '.aif', '.cda', '.mpa', '.wpl']
EXT_VIDEO = ['.mp4', '.mia', '.m4v', '.f4vv', '.f4a', '.m4b', '.m4r', '.avi', '.wma', '.flv', '.mkv']
EXT_IMAGES = ['.jpeg', '.png', '.svg', '.gif', '.bmp', '.nef', '.jpg']
EXT_DOCUMENTS = ['.txt', '.pdf', '.doc', '.docx', '.odt', '.html']
EXT_PPT = ['.ppt', '.pptx', '.pps']
EXT_EXCEL = ['.xlsx', '.xls']
EXT_ZIP = ['.zip', '.rar']
EXT_INSTALL = ['.exe', '.iso', '.bin', '.torrent']